import type { CharacterConfig } from './types';

/**
 * Body zone CSS class for each layer tag.
 *
 * Breathing animation: each zone has a different amplitude.
 * Chest rises most → head follows → hair trails → arms follow body → lower body stays.
 *
 * Some layers get an extra animation class (hair sway, headwear bob).
 */
const ZONE_MAP: Record<string, string> = {
  // Torso — most movement (chest breathing)
  'topwear':    'jp-zone--torso',
  'neck':       'jp-zone--torso',
  'neckwear':   'jp-zone--torso',
  // Head — follows chest, slightly less
  'face':       'jp-zone--head',
  'nose':       'jp-zone--head',
  'mouth':      'jp-zone--head',
  'ears-r':     'jp-zone--head',
  'ears-l':     'jp-zone--head',
  'eyebrow-r':  'jp-zone--head',
  'eyebrow-l':  'jp-zone--head',
  'eyelash-r':  'jp-zone--head',
  'eyelash-l':  'jp-zone--head',
  'eyewhite-r': 'jp-zone--head',
  'eyewhite-l': 'jp-zone--head',
  'irides-r':   'jp-zone--head',
  'irides-l':   'jp-zone--head',
  'eyewear':    'jp-zone--head',
  'headwear':   'jp-zone--head',
  // Hair — secondary motion, slight delay + own sway
  'front hair': 'jp-zone--hair',
  'back hair':  'jp-zone--hair',
  // Arms — follow torso rhythm, own subtle sway
  'handwear-r': 'jp-zone--arms',
  'handwear-l': 'jp-zone--arms',
  // Lower body — planted, no breathing
  'bottomwear': 'jp-zone--lower',
  'legwear':    'jp-zone--lower',
  'footwear':   'jp-zone--lower',
  // Objects — follow torso
  'objects':    'jp-zone--torso',
};

function layerClass(tag: string): string {
  return ZONE_MAP[tag] || '';
}

/**
 * Layer ID for JS-driven animations (blink).
 * Returns an ID string if the layer needs JS control.
 */
function layerId(tag: string): string | undefined {
  if (tag.startsWith('eyelash')) return tag;    // eyelash-r, eyelash-l
  if (tag.startsWith('eyewhite')) return tag;   // eyewhite-r, eyewhite-l
  if (tag.startsWith('irides')) return tag;     // irides-r, irides-l
  return undefined;
}

/**
 * Render order fixes: neck must render AFTER topwear (skin shows above collar).
 * API depth_median often puts neck behind topwear, which hides the neck.
 */
function fixRenderOrder(layers: { tag: string }[]): void {
  const neckIdx = layers.findIndex((l) => l.tag === 'neck');
  const topwearIdx = layers.findIndex((l) => l.tag === 'topwear');
  if (neckIdx >= 0 && topwearIdx >= 0 && neckIdx < topwearIdx) {
    // Move neck to right after topwear
    const [neck] = layers.splice(neckIdx, 1);
    const newTopwearIdx = layers.findIndex((l) => l.tag === 'topwear');
    layers.splice(newTopwearIdx + 1, 0, neck);
  }
}

/**
 * Build layer configs from metadata JSON.
 * Layers are rendered in metadata order (depth_median descending = back → front),
 * with fixRenderOrder applied for known depth errors.
 */
// eslint-disable-next-line @typescript-eslint/no-explicit-any
function buildLayers(metadata: any) {
  const layers = metadata.layers.map((l: { tag: string; xyxy: number[]; pivot?: { x: number; y: number }; held_by?: string }) => {
    const [x1, y1, x2, y2] = l.xyxy;
    const safeName = l.tag.replace(/ /g, '_').replace(/\//g, '_');
    return {
      file: `${safeName}.webp`,
      tag: l.tag,
      left: x1,
      top: y1,
      width: x2 - x1,
      height: y2 - y1,
      cssClass: layerClass(l.tag),
      id: layerId(l.tag),
      pivot: l.pivot,
      heldBy: l.held_by,
    };
  });
  fixRenderOrder(layers);
  return layers;
}

// Import metadata (generated by run_seethrough.py)
import isayaMeta from '../../public/layers/isaya/metadata.json';
import algramMeta from '../../public/layers/algram/metadata.json';
import jennyMeta from '../../public/layers/jenny/metadata.json';

export const CHARACTERS: CharacterConfig[] = [
  {
    id: 'isaya',
    name: 'Isaya',
    status: 'Drawing',
    statusEmoji: '🎨',
    mode: 'layered',
    layers: buildLayers(isayaMeta),
    stageSize: isayaMeta.frame_size[0],
    x: 50,
    y: 45,
    scale: 0.26,
    greeting: '...working on a new piece',
  },
  {
    id: 'algram',
    name: 'Algram',
    status: 'Playing guitar',
    statusEmoji: '🎸',
    mode: 'layered',
    layers: buildLayers(algramMeta),
    stageSize: algramMeta.frame_size[0],
    x: 20,
    y: 55,
    scale: 0.25,
    greeting: 'Hey! Wanna jam together?',
  },
  {
    id: 'jenny',
    name: 'Jenny',
    status: 'Coding',
    statusEmoji: '💻',
    mode: 'layered',
    layers: buildLayers(jennyMeta),
    stageSize: jennyMeta.frame_size[0],
    x: 78,
    y: 50,
    scale: 0.25,
    greeting: 'Just fixed a bug~',
  },
];
