import type { CharacterConfig } from './types';

/**
 * Animation CSS class mapping based on layer tag.
 * Tags from See-through API may contain spaces/hyphens.
 */
function layerClass(tag: string): string | undefined {
  if (tag === 'back hair') return 'jp-layer--back-hair';
  if (tag === 'front hair') return 'jp-layer--front-hair';
  if (tag === 'headwear') return 'jp-layer--headwear';
  return undefined;
}

/**
 * Layer ID for JS-driven animations (blink).
 * Returns an ID string if the layer needs JS control.
 */
function layerId(tag: string): string | undefined {
  if (tag.startsWith('eyelash')) return tag;    // eyelash-r, eyelash-l
  if (tag.startsWith('eyewhite')) return tag;   // eyewhite-r, eyewhite-l
  if (tag.startsWith('irides')) return tag;     // irides-r, irides-l
  return undefined;
}

/**
 * Semantic render order (back → front).
 * API returns layers by depth_median which isn't always visually correct.
 * Lower number = rendered first (behind).
 */
const RENDER_ORDER: Record<string, number> = {
  'back hair':   0,
  'legwear':     10,
  'footwear':    11,
  'bottomwear':  12,
  'objects':     15,
  'neck':        20,
  'topwear':     25,
  'handwear-l':  30,
  'handwear-r':  31,
  'ears-l':      35,
  'ears-r':      36,
  'face':        40,
  'nose':        41,
  'mouth':       42,
  'eyewhite-r':  50,
  'eyewhite-l':  51,
  'irides-r':    52,
  'irides-l':    53,
  'eyelash-r':   54,
  'eyelash-l':   55,
  'eyebrow-r':   56,
  'eyebrow-l':   57,
  'eyewear':     60,
  'front hair':  70,
  'headwear':    80,  // headwear (headphones etc.) on top of everything
};

/**
 * Build layer configs from metadata JSON, sorted by semantic render order.
 */
// eslint-disable-next-line @typescript-eslint/no-explicit-any
function buildLayers(metadata: any) {
  const layers = metadata.layers.map((l: { tag: string; xyxy: number[] }) => {
    const [x1, y1, x2, y2] = l.xyxy;
    const safeName = l.tag.replace(/ /g, '_').replace(/\//g, '_');
    return {
      file: `${safeName}.png`,
      tag: l.tag,
      left: x1,
      top: y1,
      width: x2 - x1,
      height: y2 - y1,
      cssClass: layerClass(l.tag),
      id: layerId(l.tag),
    };
  });

  // Sort by semantic render order (back → front)
  layers.sort((a: { tag: string }, b: { tag: string }) =>
    (RENDER_ORDER[a.tag] ?? 99) - (RENDER_ORDER[b.tag] ?? 99)
  );

  return layers;
}

// Import metadata (generated by run_seethrough.py)
import isayaMeta from '../../public/layers/isaya/metadata.json';
import algramMeta from '../../public/layers/algram/metadata.json';
import jennyMeta from '../../public/layers/jenny/metadata.json';

export const CHARACTERS: CharacterConfig[] = [
  {
    id: 'isaya',
    name: 'Isaya',
    status: 'Drawing',
    statusEmoji: '🎨',
    mode: 'layered',
    layers: buildLayers(isayaMeta),
    stageSize: isayaMeta.frame_size[0],
    x: 50,
    y: 45,
    scale: 0.26,
    greeting: '...working on a new piece',
  },
  {
    id: 'algram',
    name: 'Algram',
    status: 'Playing guitar',
    statusEmoji: '🎸',
    mode: 'layered',
    layers: buildLayers(algramMeta),
    stageSize: algramMeta.frame_size[0],
    x: 20,
    y: 55,
    scale: 0.25,
    greeting: 'Hey! Wanna jam together?',
  },
  {
    id: 'jenny',
    name: 'Jenny',
    status: 'Coding',
    statusEmoji: '💻',
    mode: 'layered',
    layers: buildLayers(jennyMeta),
    stageSize: jennyMeta.frame_size[0],
    x: 78,
    y: 50,
    scale: 0.25,
    greeting: 'Just fixed a bug~',
  },
];
